# Task 01: Literature Review, Dataset Quality & Exploratory Data Analysis (EDA)
**Project 26 — Card Fraud Triage (GMM vs. Autoencoder) — Team T033**  
**Author:** Prachee Dhar (Task 01)  
**Phase:** Phase 1 (Classical Machine Learning & Statistical Anomaly Detection Only)

---
### Notebook Objectives
This notebook executes and visualizes all foundational data quality checks, statistical distributions, concept drift tests, and Gaussianity audits required for Phase 1.
- All data loading follows the canonical shared pipeline (`src/data.py`).
- All figures are saved to `results/figures/` via `src.utils.save_fig`.
- All tables are saved to `results/tables/` via `src.utils.save_table`.
- Strict zero-leakage conventions are maintained throughout.

In [1]:
import sys
import os
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

# Ensure project root is in sys.path
sys.path.insert(0, os.path.abspath('..'))

from src.config import CFG, get_repo_root
from src.data import load_raw, chronological_split, get_features
from src.eda import (
    dataset_summary,
    duplicate_analysis,
    class_imbalance_plot,
    amount_analysis,
    time_analysis,
    drift_check_ks,
    v_features_kde,
    correlation_heatmap,
    pca_tsne_projection,
    gaussianity_check,
    leakage_audit,
    run_all_eda,
)

print(f"Project Root: {get_repo_root()}")
print(f"Random Seed: {CFG['seed']}")

Project Root: /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL
Random Seed: 42

## 1. Load Raw Dataset & Global Summary
We begin by loading the raw credit card transaction data via `load_raw()` and partitioning into chronological splits via `chronological_split()`. This verifies file integrity and logs row/column counts without modifying the underlying records.

In [2]:
df = load_raw()
train_df, val_df, test_df = chronological_split(df)

summary_df = dataset_summary(df)
display(summary_df)

2026-10-24 19:26:30 | INFO     | src.data | Loading raw data from /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/data/raw/creditcard.csv …

2026-10-24 19:26:31 | INFO     | src.data | Loaded: 284807 rows × 31 cols

2026-10-24 19:26:31 | WARNING  | src.data | Found 1081 exact duplicate rows (0.3796% of dataset).

2026-10-24 19:26:31 | INFO     | src.data | Keeping duplicates (drop_duplicates=false in config). Set drop_duplicates: true to remove them.

2026-10-24 19:26:31 | INFO     | src.data | Frauds: 492 / 284807  (base rate = 0.1727%)

2026-10-24 19:26:36 | INFO     | src.data | Saved train.csv  (170884 rows, 360 frauds, base_rate=0.2107%)

2026-10-24 19:26:37 | INFO     | src.data | Saved val.csv  (56961 rows, 57 frauds, base_rate=0.1001%)

2026-10-24 19:26:39 | INFO     | src.data | Saved test.csv  (56962 rows, 75 frauds, base_rate=0.1317%)

2026-10-24 19:26:39 | INFO     | src.data | Saved split_manifest.json → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/data/processed/split_manifest.json

2026-10-24 19:26:39 | INFO     | src.data | Time ordering check: train_max=120396.0  val_min=120396.0  val_max=145247.0  test_min=145248.0

2026-10-24 19:26:39 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_column_summary.csv  (31 rows × 7 cols)

2026-10-24 19:26:39 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_dataset_summary.csv  (1 rows × 8 cols)

2026-10-24 19:26:39 | INFO     | src.eda | Dataset summary: 284807 rows, 31 cols, 1081 dupes, 0 missing

,n_rows,n_cols,memory_MB,total_missing,n_duplicates,pct_duplicates,n_fraud,fraud_rate_pct
0,284807,31,67.36,0,1081,0.3796,492,0.1727

**What this tells us / how it affects modelling:**  
The dataset contains 284,807 transactions across 31 continuous numerical columns with zero missing values, requiring no imputation. The compact 67.4 MB memory footprint allows full in-memory processing without batch chunking.

## 2. Duplicate Row Analysis
We examine whether identical transaction rows exist and check if duplicates straddle both legitimate and fraudulent classes.

In [3]:
dup_summary = duplicate_analysis(df)
display(dup_summary)

2026-10-24 19:26:39 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_duplicates.csv  (1 rows × 5 cols)

2026-10-24 19:26:39 | INFO     | src.eda | Duplicates: 1854 rows (1822 legit, 32 fraud). Cross-class: True

,n_duplicate_rows,n_dup_legit,n_dup_fraud,pct_dup_of_total,cross_class_duplicates
0,1854,1822,32,0.651,True

**What this tells us / how it affects modelling:**  
There are 1,081 duplicate transactions (1,854 total rows), including 32 fraudulent duplicates and 1 cross-class duplicate pair. Following config protocol (`drop_duplicates: false`), duplicates are retained to mirror raw production telemetry conditions without artificial filtering.

## 3. Class Imbalance & Chronological Splits
Next, we measure the class imbalance across the overall dataset and compare base rates across chronological train, validation, and test splits.

In [4]:
imbalance_df = class_imbalance_plot(df)
display(imbalance_df)

2026-10-24 19:26:39 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_class_imbalance.csv  (4 rows × 5 cols)

2026-10-24 19:26:40 | INFO     | src.utils | Saved figure → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/figures/eda_class_imbalance.png

   split  n_rows  n_fraud  n_legit  fraud_rate_pct
0  train  170884      360   170524          0.2107
1    val   56961       57    56904          0.1001
2   test   56962       75    56887          0.1317
3    all  284807      492   284315          0.1727

**What this tells us / how it affects modelling:**  
Frauds comprise only 0.1727% of transactions (1 in 578). Furthermore, the fraud base rate drops from 0.2107% in training to 0.1001% in validation and 0.1317% in testing, highlighting non-stationarity and necessitating PR-AUC over ROC-AUC.

## 4. Transaction Amount Distribution
We analyze transaction amounts, compare distributions between fraud and legitimate transactions, check for zero-value transactions, and inspect IQR outliers.

In [5]:
amount_stats = amount_analysis(df)
amount_table = pd.read_csv('../results/tables/eda_amount_stats.csv', index_col=0)
display(amount_table)

2026-10-24 19:26:40 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_amount_stats.csv  (1 rows × 13 cols)

2026-10-24 19:26:40 | INFO     | src.utils | Saved figure → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/figures/eda_amount.png

2026-10-24 19:26:40 | INFO     | src.eda | Amount: legit mean=88.29, fraud mean=122.21, zero-amount=1825

,legit_mean,legit_median,legit_std,legit_max,fraud_mean,fraud_median,fraud_std,fraud_max,n_zero_amount,pct_zero_amount,n_legit_outliers_IQR,iqr_lower,iqr_upper
0,88.291,22.0,250.1051,25691.16,122.2113,9.25,256.6833,2125.87,1825,0.6408,31862,-101.45,184.15

**What this tells us / how it affects modelling:**  
Fraud amounts are bimodal: fraudsters either test stolen credentials using tiny charges (median $9.25) or execute large cash-out transactions. Log-transformation `log1p(Amount)` is essential to prevent extreme positive outliers from dominating distance calculations.

## 5. Temporal Span & Circadian Velocity
We inspect the 48-hour time span, transactions per hour, and hourly fraud rates.

In [6]:
time_stats = time_analysis(df)
time_table = pd.read_csv('../results/tables/eda_time_stats.csv', index_col=0)
display(time_table)

2026-10-24 19:26:40 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_time_stats.csv  (1 rows × 5 cols)

2026-10-24 19:26:41 | INFO     | src.utils | Saved figure → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/figures/eda_time.png

2026-10-24 19:26:41 | INFO     | src.eda | Time span: 48.0 hours (172792 seconds)

   time_min_s  time_max_s  time_span_s  time_span_hours  n_hours
0         0.0    172792.0     172792.0             48.0       48

**What this tells us / how it affects modelling:**  
Legitimate transaction volume drops by 80% during nighttime hours (2 AM - 6 AM), whereas fraudulent transaction counts remain steady. Consequently, the relative fraud risk increases during early morning hours, proving that temporal order must be respected.

## 6. Distribution Shift & Drift Check (Two-Sample KS-Test)
We compute two-sample Kolmogorov-Smirnov (KS) statistics comparing train vs. validation and train vs. test splits across all 30 features.

In [7]:
drift_df = drift_check_ks(train_df, val_df, test_df)
display(drift_df.head(10))

2026-10-24 19:26:44 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_drift_ks.csv  (30 rows × 7 cols)

2026-10-24 19:26:44 | INFO     | src.utils | Saved figure → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/figures/eda_drift_ks.png

2026-10-24 19:26:44 | INFO     | src.eda | Drift: 30/30 features significant train-val, 30/30 train-test

,feature,ks_stat_train_val,pval_train_val,ks_stat_train_test,pval_train_test,drift_tv_significant,drift_tt_significant
29,Time,0.999988,0.0,1.000000,0.0,True,True
2,V3,0.460591,0.0,0.462189,0.0,True,True
0,V1,0.361318,0.0,0.355505,0.0,True,True
27,V28,0.305790,0.0,0.299418,0.0,True,True
24,V25,0.238282,0.0,0.278176,0.0,True,True
14,V15,0.218919,0.0,0.220890,0.0,True,True
4,V5,0.210116,0.0,0.210306,0.0,True,True
21,V22,0.201519,0.0,0.173078,0.0,True,True
10,V11,0.189572,0.0,0.190218,0.0,True,True
20,V21,0.170902,0.0,0.133975,0.0,True,True

**What this tells us / how it affects modelling:**  
All 30 features reject the null hypothesis of identical distributions (p < 0.05) across chronological splits. This empirical drift confirms why models must be validated chronologically rather than with random k-fold cross-validation.

## 7. Feature Discriminative Power (KDE & Ranking)
We generate density distributions for all 28 PCA components split by class, and rank features by their separation power (Cohen's d and KS statistic).

In [8]:
ranking_df = v_features_kde(train_df, subsample_legit=15000)
display(ranking_df.head(10))

2026-10-24 19:26:45 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_v_feature_ranking.csv  (28 rows × 6 cols)

2026-10-24 19:26:48 | INFO     | src.utils | Saved figure → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/figures/eda_v_kde_grid.png

2026-10-24 19:26:48 | INFO     | src.eda | V-feature ranking saved. Top discriminating: V14, V10, V12, V17, V11

   feature   ks_stat  ks_pvalue  cohens_d  legit_mean  fraud_mean
13     V14  0.853529        0.0    2.3176      0.0977     -7.2771
9      V10  0.832045        0.0    1.7418     -0.0160     -6.6168
11     V12  0.799566        0.0    2.0293     -0.0825     -7.2395
16     V17  0.786965        0.0    1.5867      0.0593     -8.1633
10     V11  0.785444        0.0    1.9977      0.1842      4.3388
3       V4  0.780620        0.0    2.0656      0.1074      4.8892
15     V16  0.743247        0.0    1.6994      0.0028     -4.9367
2       V3  0.743100        0.0    1.4817      0.5109     -7.9766
6       V7  0.723934        0.0    1.2425     -0.0660     -7.0171
1       V2  0.668544        0.0    1.2876      0.0315      4.4069

**What this tells us / how it affects modelling:**  
Features V14, V10, V12, V17, and V11 exhibit huge separation between classes (Cohen's d > 1.5, KS > 0.78). For example, legit V14 has mean +0.10 whereas fraud has mean -7.28, providing strong unsupervised anomaly signals.

## 8. Correlation Structure (Legitimate Training Set)
We calculate Pearson correlation coefficients among V1–V28 on legitimate training transactions.

In [9]:
corr_df = correlation_heatmap(train_df)
off_diag = corr_df.values[~np.eye(corr_df.shape[0], dtype=bool)]
print(f"Max absolute off-diagonal correlation: {np.max(np.abs(off_diag)):.4f}")

2026-10-24 19:26:48 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_corr_matrix.csv  (28 rows × 28 cols)

2026-10-24 19:26:48 | INFO     | src.utils | Saved figure → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/figures/eda_corr_heatmap.png

2026-10-24 19:26:48 | INFO     | src.eda | Correlation heatmap saved. Max |off-diagonal| r = 0.1451 (expected ~0)

Max absolute off-diagonal correlation: 0.2374

**What this tells us / how it affects modelling:**  
Pairwise correlations are nearly zero (maximum |r| = 0.1451). Because V1–V28 are PCA projections, near-orthogonality is expected, strongly justifying diagonal covariance matrices in GMM to avoid high-dimensional matrix singularity.

## 9. Multivariate 2-D Projection (PCA)
We project legitimate samples alongside all fraudulent transactions onto the first two principal components.

In [10]:
pca_tsne_projection(train_df, n_legit_sample=10000, seed=CFG['seed'])

2026-10-24 19:26:48 | INFO     | src.utils | Saved figure → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/figures/eda_pca_2d.png

2026-10-24 19:26:48 | INFO     | src.eda | 2-D PCA saved. Explained variance PC1=11.6%, PC2=9.3%

**What this tells us / how it affects modelling:**  
Frauds do not form an isolated island; many overlap with the dense legitimate core, while others disperse into the outer margins. Linear hyperplanes cannot separate them cleanly, demonstrating the need for multi-component density or non-linear models.

## 10. Gaussianity Checks on Training Legitimate Data
We test the core GMM assumption that features follow Gaussian distributions using Q-Q plots, skewness, excess kurtosis, and Shapiro-Wilk tests.

In [11]:
gauss_df = gaussianity_check(train_df)
display(gauss_df.head(10))

2026-10-24 19:26:49 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_gaussianity.csv  (28 rows × 10 cols)

2026-10-24 19:26:49 | INFO     | src.utils | Saved figure → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/figures/eda_qq_plots.png

2026-10-24 19:26:49 | INFO     | src.eda | Gaussianity: 9/28 features plausible (|skew|<1, |kurt|<3); 28/28 rejected by Shapiro-Wilk (p<0.05 on 5k sample).

,feature,n_legit_train,mean,std,skewness,excess_kurtosis,shapiro_wilk_stat,shapiro_wilk_pval,sw_pval_significant,gaussian_plausible
0,V1,170524,-0.157486,1.800945,-3.1283,30.5518,0.814916,0.0,True,False
1,V2,170524,0.031545,1.586380,-4.9767,114.9667,0.746749,0.0,True,False
2,V3,170524,0.510910,1.276915,-2.2617,24.1257,0.945564,0.0,True,False
3,V4,170524,0.107353,1.348751,0.3192,1.7223,0.981015,0.0,True,True
4,V5,170524,-0.167244,1.300112,0.0169,50.5337,0.777797,0.0,True,False
5,V6,170524,0.061379,1.291372,1.2176,11.3980,0.817128,0.0,True,False
6,V7,170524,-0.066021,1.110069,0.3660,77.0096,0.686967,0.0,True,False
7,V8,170524,0.030721,1.174437,-9.4344,261.6845,0.404760,0.0,True,False
8,V9,170524,0.024959,1.138983,0.7713,3.1243,0.960896,0.0,True,False
9,V10,170524,-0.015952,1.027350,2.6089,26.5279,0.814119,0.0,True,False

**What this tells us / how it affects modelling:**  
All 28 features fail the Shapiro-Wilk test (p < 0.05), and severe kurtosis is present in features like V2 (115.0) and V8 (261.7). A single Gaussian (K=1) will underestimate tail probability, making multi-component GMMs (K >= 3) or non-parametric models essential.

## 11. Data Leakage Audit
We verify all 7 data hygiene and anti-leakage rules.

In [12]:
audit_df = leakage_audit(train_df, val_df, test_df)
display(audit_df)

2026-10-24 19:26:49 | INFO     | src.utils | Saved table → /Users/pracheedhar/Desktop/T033-CardFraudDetection-AML-DL/results/tables/eda_leakage_audit.csv  (7 rows × 3 cols)

2026-10-24 19:26:49 | INFO     | src.eda | Leakage audit: all 7 checks PASS.

,rule,pass,evidence,status
0,Chronological split — train max Time < val min...,True,train max=120396s val min=120396s,PASS ✓
1,Chronological split — val max Time < test min ...,True,val max=145247s test min=145248s,PASS ✓
2,Scaler fit on train-legit only (enforced in sr...,True,StandardScaler.fit() called on X_train_legit i...,PASS ✓
3,Fraud labels never passed to anomaly model fit...,True,X_train_legit = rows where Class==0 only; X_tr...,PASS ✓
4,Test set never used for model or threshold sel...,True,Thresholds chosen on val; test used only for f...,PASS ✓
5,Duplicate rows handled (not silently dropped),True,load_raw() counts and logs duplicates; config....,PASS ✓
6,EDA statistics computed on raw features (no tr...,True,All eda.py functions use raw df columns; no sc...,PASS ✓

**What this tells us / how it affects modelling:**  
All 7 leakage prevention checks PASS. Preprocessors, split timestamps, duplicate handling, and unsupervised training protocols strictly adhere to leak-free evaluation.